Add linux -> windows cross-compilation
conda-forge/polars-feedstock pull request #187
Opened 2023-10-16 13:50 UTC by pavelzw

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2023-10-17 09:01 UTC, pavelzw commented on recipe/meta.yaml
>    skip: true  # [win and python_impl=="pypy"]
```suggestion
  skip: true  # [win and python_impl=="pypy"]
  skip: true  # [target_platform != "win-64"]
```

2023-10-17 09:01 UTC, pavelzw commented
@conda-forge-admin, please rerender

2023-10-20 09:03 UTC, 0xbe7a commented
depends on https://github.com/conda-forge/maturin-feedstock/pull/109 and https://github.com/conda-forge/rust-activation-feedstock/pull/38

2023-10-26 09:06 UTC, 0xbe7a commented
@conda-forge-admin, please restart ci

2023-10-26 11:24 UTC, xhochy requested changes
Before we merge, we should definitely rerender this to ensure that nothing breaks other systems.

2023-10-26 11:24 UTC, xhochy commented on recipe/meta.yaml
> +    - posix                               # [win and not (build_platform == "linux-64" and target_platform == "win-64")]
```suggestion
    - posix                               # [build_platform == "win-64"]
```

2023-10-26 11:24 UTC, xhochy commented on recipe/meta.yaml
> +    - cross-python_{{ target_platform }}  # [build_platform != target_platform and not (build_platform == "linux-64" and target_platform == "win-64")]
Can you add a comment why this and `compiler('c')` is excluded in the win-cross situation?

2023-10-26 12:20 UTC, pavelzw commented
You can install the builds from [`45450e1` (#187)](https://github.com/conda-forge/polars-feedstock/pull/187/commits/45450e1d3d74787812092f215fadc1e80d73801d) using

```
micromamba install -c https://repo.prefix.dev/test-polars polars=0.19.11
```

2023-10-26 12:24 UTC, pavelzw commented
I did some light testing with the cross-compiled build and everything seems to work 👍🏻

2023-10-26 14:30 UTC, xhochy commented
We will need https://github.com/conda-forge/clang-win-activation-feedstock/pull/31 to get rid of 

```
2023-10-26T13:47:26.8314466Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-stdio-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:26.8319964Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2023-10-26T13:47:26.8322721Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-heap-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:26.8324106Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2023-10-26T13:47:26.8330566Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-runtime-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:27.8297454Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2023-10-26T13:47:27.8299486Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-convert-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:27.8306434Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2023-10-26T13:47:27.8307935Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-string-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:27.8309333Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
2023-10-26T13:47:27.8313485Z WARNING (polars,lib/site-packages/polars/polars.pyd): Needed DSO api-ms-win-crt-math-l1-1-0.dll found in ['ucrt']
2023-10-26T13:47:27.8314925Z WARNING (polars,lib/site-packages/polars/polars.pyd): .. but ['ucrt'] not in reqs/run, (i.e. it is overlinking) (likely) or a missing dependency (less likely)
```

2023-10-26 15:17 UTC, xhochy approved these changes

2023-10-26 15:18 UTC, 0xbe7a commented
@conda-forge-admin, please restart ci

2023-10-26 17:01 UTC, merged